MODE: "LICENSE_PROVISIONED_CRON,ACCOUNT_TRAITS_CRON"
CLUSTER_ID: "TEST"
CG_MONGODB_DB_NAME: "harness"
CG_MONGODB_URL: "mongodb://localhost:27017/harness"
NG_MONGODB_DB_NAME: "ng-harness"
NG_MONGODB_URL: "mongodb://localhost:27017/ng-harness"

SEGMENT_ENABLED: false
SEGMENT_API_KEY: placeholder
SEGMENT_URL: "https://api.segment.io"