MODE: "LICENSE_PROVISIONED_CRON"
CG_MONGODB_DB_NAME: "harness"
CG_MONGODB_URL: "mongodb://localhost:27017/harness"

SEGMENT_ENABLED: false
SEGMENT_API_KEY: placeholder
SEGMENT_URL: "https://api.segment.io"